# Add a box to local machine: 
#   vagrant box add action-test/ubuntu-18.04-server-amd64
#   vagrant box list
#   vagrant box -help
# ---------------------------------
# To start VM:
#   vagrant up
# To stop VM:  
#   vagrant halt
# SSH:
#   vagrant ssh
# ---------------------------------
# user: vagrant
# password: vagrant
# 
# Ubuntu 18.04.4 Server
# vagrant init action-test/ubuntu-18.04-server-amd64 \
#  --box-version 20200218.05
# vagrant up

Vagrant.configure("2") do |config|

  # Ubuntu 18.04.4 Server
  config.vm.box = "action-test/ubuntu-18.04-server-amd64"
  config.vm.box_version = "20200218.05"
  config.vm.provider "virtualbox" do |v|
    v.gui = true
    v.name = "vagrant-ubuntu-server"
    v.memory = 2048
    v.cpus = 2
  end
  config.vm.provision "shell", path: "bootstrap.sh", args: ["vagrant"]
  config.vm.provision "shell", path: "user-config.sh", privileged: false
end