# Add a box to local machine: 
#   vagrant box add peru/ubuntu-20.04-desktop-amd64
#   vagrant box list
#   vagrant box -help
# ---------------------------------
# To start VM:
#   vagrant up
# To stop VM:  
#   vagrant halt
# SSH:
#   vagrant ssh
# ---------------------------------
# user: vagrant
# password: vagrant 
# Ubuntu 18.04.4 Desktop
# vagrant init peru/ubuntu-20.04-desktop-amd64 \
#   --box-version 20200207.01
# vagrant up

Vagrant.configure("2") do |config|
  # Ubuntu 20.04 Desktop
  config.vm.box = "peru/ubuntu-20.04-desktop-amd64"
  config.vm.provider "virtualbox" do |v|
    v.gui = true
    v.name = "master"
    v.memory = 4096
    v.cpus = 2
  end
  config.vm.provision "shell", path: "bootstrap.sh", args: ["vagrant"]
  config.vm.provision "shell", path: "install_kubectl.sh", args: ["vagrant"]
  config.vm.provision "shell", path: "install_helm.sh", args: ["vagrant"]
  config.vm.provision "shell", path: "user-config.sh", privileged: false
end